### ISSUE TITLE
UnauthorizedError: Missing or bad formatted authorization header

### ISSUE THREAD

**Issue by useo6** [fastify/fastify-basic-auth#11]
I'm using fastify-swagger to generate my Swagger API documentation. Now I want protect this documentation using this plugin but I'm always getting the following error:

> UnauthorizedError: Missing or bad formatted authorization header

I've added the fastify-basic-auth plugin as described:

```
  const fastify = require('fastify')({
    logger: false
  })

  fastify.register(require('fastify-basic-auth'), {
    validate: async function (...args) {
      console.log(args)
    },
    authenticate: true // WWW-Authenticate: Basic
  })

  fastify.after(() => {
    fastify.addHook('preHandler', fastify.basicAuth)
  })

  await fastify.listen(8888)
```

According to the documentation, setting the "authenticate" option to true:

> This can be useful in situations where we want to trigger client-side authentication interfaces - for instance the browser authentication dialog.
> 
> As a boolean setting authenticate to true will set a header like so: WWW-Authenticate: Basic. When false, no header is added. This is the default.

But I'm get no dialog where I can enter my credentials. Instead I'm getting the "UnauthorizedError". What I'm doing wrong here?

**Comment by StarpTech** [comment]
Hi @useo6, in order to analyse our issue we need the full request (headers etc...) According to error message it really looks like you just missed the `authorization``header or use a wrong [value](https://github.com/jshttp/basic-auth/blob/master/index.js#L38)

**Comment by useo6** [comment]
This is my request header:

> Host: localhost:8888
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
> Accept-Language: de,en-US;q=0.7,en;q=0.3
> Accept-Encoding: gzip, deflate
> Connection: keep-alive
> Cookie: hibext_instdsigdipv2=1; sessionId=a173c320-b2b2-4f33-950d-2cde4927b47f
> Upgrade-Insecure-Requests: 1
> If-Modified-Since: Sat, 26 Oct 1985 08:15:00 GMT
> If-None-Match: W/"658-7438674ba0"
> Cache-Control: max-age=0, no-cache
> Pragma: no-cache

I know, the browser doesn't pass any auth-information in the request to fastify. The reason for this is that the browser never shows a dialog to authenticate. What I expect is that I get a browser dialog (like shown here: https://stackoverflow.com/questions/15177325/how-to-display-http-401-basic-authentication-dialog) where I can enter my credentials. But this dialog is never shown... instead I'm getting the "UnauthorizedError" in fastify...

**Comment by StarpTech** [comment]
I tested it and it works

```js
const fastify = require('fastify')()

fastify.register(require('.'), {
    validate: async function (...args) {
      console.log(args)
    },
    authenticate: true // WWW-Authenticate: Basic
  })

fastify.after(() => {
    fastify.addHook('preHandler', fastify.basicAuth)
    fastify.route({
        method: 'GET',
        url: '/',
        handler: async (req, reply) => {
          return { hello: 'world' }
        }
      })
  })

fastify.listen(5000, (err, address) => {
  if (err) throw err;
  fastify.log.info(`server listening on ${address}`);
});
```
Please provide a full reproducible example if you want that we investigate further.

**Comment by foobst** [comment]
Ok, I finally figured out that the problem was my global error handler (setErrorHandler on fastify instance). I returned error code 500 whenever an error occurred. Thank you for the support!

**Comment by useo6** [comment]
Ok, I finally figured out that the problem was my global error handler (setErrorHandler on fastify instance). I returned error code 500 whenever an error occurred. Thank you for the support!

**Comment by Vijaysinh** [comment]
> Ok, I finally figured out that the problem was my global error handler (setErrorHandler on fastify instance). I returned error code 500 whenever an error occurred. Thank you for the support!

@useo6 I am also facing same issue , previously it was asking HTTP popup for login but after adding setErrorHandler it giving direct error to browser, how you fixed this? could you please share code?

**Comment by abhishek73magar** [comment]
@Vijaysinh i have resolved the same issue, its late but here is the code snippet i used 

```
app.setErrorHandler((error: FastifyError, req, reply) => {
    // global error handler
    if(error.code === 'FST_BASIC_AUTH_MISSING_OR_BAD_AUTHORIZATION_HEADER') {
      // only handle basic auth errors here, other errors will be handled by the global error handler
      return reply.send(error)
    }

    if(error instanceof HttpError) {
      return reply.status(error.statusCode).send({
        statusCode: error.statusCode,
        message: error.message,
        errors: error.errors
      })
    }

    const messagePayload = {
      statusCode: reply.statusCode === 200 ? 400 : reply.statusCode,
      message: error.message
    }
    reply.code(messagePayload.statusCode).send(error)
  })
}
```
