### ISSUE TITLE
Set custom auth header

### ISSUE THREAD

**Issue by mattyod** [fastify/fastify-basic-auth#47]
## 🚀 Feature Proposal

Add the ability to set a custom authorization header.

If a `header` property exists in options then use basic-auths `auth.parse()` method rather than `auth()`.

## Motivation

Some of our services sit behind an API Gateway that transfers incoming `authorization` headers onto a custom `x-forwarded-authorization` header. Unfortunately that API Gateway does not provide basic authentication checks 🤷 , so authentication still needs to be done within the service. (there are other benefits to the Gateway in case you are wondering 😄 ).

## Example

```
fastify.register(basicAuth, { validate, authenticate, header: 'x-forwarded-authorization` }
```

**Comment by Eomm** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by jsumners** [comment]
I'm not clear why the gateway would violate the spec and necessitate this module to do the same -- https://datatracker.ietf.org/doc/html/rfc7235#section-4.2

**Comment by mattyod** [comment]
Thanks, I'll try and get something up in a PR shortly.

> I'm not clear why the gateway would violate the spec and necessitate this module to do the same

It's a fair question, I guess they see this as a gateway to a system rather than a proxy to another API, though I'm speculating.

https://cloud.google.com/endpoints/docs/openapi/service-account-authentication#receiving_authenticated_results_in_your_api

**Comment by mcollina** [comment]
PRs are welcome!

**Comment by mattyod** [comment]
Thank you for accepting a PR on this, it's a great help.

A member of our platform team has raised a case with GCP asking about the reasoning behind moving authentication onto the `x-forwarded-authorization` header, and as you point out, breaking the specification. I'll try to update here with the outcome of that.

**Comment by t-pk** [comment]
Tried set header but still not working. still by default still get the header with the key is: **Authorization**

**Comment by mattyod** [comment]
The update here doesn't do anything to modify the Authorization header, it informs the fastify-basic-auth plugin to perform checks against a second named header rather than whatever is on the Authorization header.
