### ISSUE TITLE
Allow custom decorate name

### ISSUE THREAD

**Issue by bcomnes** [fastify/fastify-basic-auth#97]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I have a use case where I want to have 2 different basic auth functions for different routes. It would be nice if I could register the basic-auth plugin twice and customize the decorate name:

https://github.com/fastify/fastify-basic-auth/blob/96bcbf964a4c03b22157fbfe042ea7b71ab7ab9a/index.js#L15

### Motivation

I want to support different basic auth logic on different routes, and would like to register 2 different validate functions on different decorated names off of fastify. 

### Example

```js
fastify.register(require('@fastify/basic-auth'), { validate, authenticate, namespace: 'otherBasicAuth' })

fastify.after(() => {
  fastify.addHook('onRequest', otherBasicAuth)

  fastify.get('/', (req, reply) => {
    reply.send({ hello: 'world' })
  })
})
```

Something like this. Happy to contribute this.

**Comment by mcollina** [comment]
Thanks for reporting! 

I don't think this functionality is needed as you can register the same plugin twice in difference encapsulation context, check out:

```js
fastify.register(async function plugin1 (fastify) {
  fastify.register(require('@fastify/basic-auth'), { ... })
  // routes protected here according to the local config
})

fastify.register(async function plugin2 (fastify) {
  fastify.register(require('@fastify/basic-auth'), { ... })
  // routes protected here according to the local config
})
```

If you still think this functionality is needed, check out fastify-mongodb or fastify-posgresql, they both implement it.

**Comment by bcomnes** [comment]
Oh ok let me try that! I'll re open if it doesn't work for me. Thank you!
